import sys , os
from storage import object_read,object_find,GitRepository,repo_file,object_write
from objects import GitTag
from objects import GitTree
from typing import Optional,Dict,Any



def cat_file(repo: GitRepository, obj: str, fmt: Optional[bytes] = None) -> None:
    """Output the contents of a Git object.

    Args:
        repo: The repository.
        obj: The object name.
        fmt: Expected format (optional).
    """
    obj = object_read(repo, object_find(repo, obj, fmt=fmt))
    sys.stdout.buffer.write(obj.serialize())


def tree_checkout(repo: "GitRepository", tree: "GitTree", path: str) -> None:
    """Checkout a tree to a directory path.

    Args:
        repo: The repository.
        tree: The GitTree object.
        path: The destination path.
    """
    for item in tree.items:
        
        obj = object_read(repo, item.sha)
        
        dest = os.path.join(path, item.path)
        
        if obj.fmt == b'tree':
            os.mkdir(dest)
            tree_checkout(repo, obj, dest)
            
            
        elif obj.fmt == b'blob':
            with open(dest, 'wb') as f:
                f.write(obj.blobdata)
                
                

def _ref_create(repo: GitRepository, ref_name: str, sha_value: str) -> None:
    """Create a new reference.

    Args:
        repo: The Git repository instance.
        ref_name: The name of the reference.
        sha_value: The SHA hash to point to.
    """
    with open(repo_file(repo , "refs/" +ref_name) , "w") as ref_file:
        ref_file.write(sha_value + "\n")
        
def tag_create(repo: GitRepository, tag_name: str, target_ref: str = "HEAD", create_annotated_tag: bool = False, message: bytes = b"A tag generated by gitsh") -> None:
    """Create a new tag in the repository.

    Args:
        repo: The Git repository instance.
        tag_name: The name of the tag.
        target_ref: The reference to tag (default 'HEAD').
        create_annotated_tag: Whether to create an annotated tag.
        message: The tag message for annotated tags.
    """
    # find the gitobject from reference
    target_sha =object_find(repo,target_ref)
    
    if create_annotated_tag : 
        # create tag object
        tag = GitTag()
        
        tag.kvlm = dict()
        
        tag.kvlm[b"object"] =target_sha.encode()
        tag.kvlm[b"type"] = b'commit'
        tag.kvlm[b"tag"] = tag_name.encode()
        
        # add tagger details 
        name = repo.config.get("user", "name")
        email = repo.config.get("user", "email")
        tagger =f"{name} <{email}>".encode() if name and email else b'gitsh <gitsh@example.com>'
        tag.kvlm[b'tagger'] =  tagger
        
        # add message
        tag.kvlm[None] =message
        # write the tag object to git database
        tag_object_sha  =object_write(tag,repo)
        
        
        # create reference pointing to the tag object
        _ref_create(repo, "tags/" + tag_name , tag_object_sha )
        
    else: 
        # lightweight tag 
        _ref_create(repo , "tags/"+tag_name , target_sha)
        
        

def show_ref(repo: GitRepository, refs: Dict[str, Any], include_hash: bool = True, current_prefix: str = "") -> None:
    """Display references in a formatted way.

    Args:
        repo: The Git repository instance.
        refs: The dictionary of references.
        include_hash: Whether to include SHA hashes in output.
        current_prefix: The current prefix for nested references.
    """
    # add "/" if we are not at the rool level
    if current_prefix : 
        current_prefix = current_prefix + "/"
        
    for ref_name, ref_value in refs.items():
        # this is a file (final ref -> sha string)
        if isinstance(ref_value , str) :
            if include_hash:
                print(f"{ref_value} {current_prefix}{ref_name}")
            else :
                print(f"{current_prefix}{ref_name}")
                
        else :  # this is directory (nested ref)
            show_ref(
                repo,
                ref_value,
                include_hash=include_hash,
                current_prefix=f"{current_prefix}{ref_name}"
            )
            



def log_graphviz(repo: "GitRepository", sha: str, seen: Optional[set] = None) -> None:
    """Generate GraphViz dot format for commit graph.

    Args:
        repo: The repository.
        sha: The commit SHA.
        seen: Set of already processed SHAs.
    """
    if seen is None:
        seen = set()
    if sha in seen:
        return
    seen.add(sha)

    commit = object_read(repo, sha)
    assert commit.fmt == b"commit", f"Expected commit, got {commit.fmt} for {sha}"

    short_sha = sha[0:7]
    raw_message = commit.kvlm[None].decode("utf8").strip()
    subject = raw_message.splitlines()[0] if raw_message else "(no message)"
    subject = subject.replace("\\", "\\\\").replace('"', '\\"')

    author_line = commit.kvlm.get(b"author", b"").decode("utf8")
    author_name = author_line.split("<")[0].strip() if "<" in author_line else author_line

    label = f"{short_sha}\\n{subject}\\n{author_name}"
    print(f'  c_{sha} [label="{label}"]')

    parents = commit.kvlm.get(b"parent", None)
    if parents is None:
        return

    if not isinstance(parents, list):
        parents = [parents]

    for p in parents:
        p = p.decode("ascii")
        print(f"  c_{sha} -> c_{p}")
        log_graphviz(repo, p, seen)



def ls_tree(repo: "GitRepository", ref: str, recursive: Optional[bool] = None, prefix: str = "") -> None:
    """List the contents of a tree object.

    Args:
        repo: The repository.
        ref: The tree reference.
        recursive: Whether to list recursively.
        prefix: Path prefix for output.
    """
    sha = object_find(repo, ref, fmt=b"tree")
    obj = object_read(repo, sha)

    for item in obj.items:
        
        item.mode.rjust(6, b'0') # pad with leading zeros if len = 5
        type = item.mode[0:2]


        match type:
            case b"04":
                type = "tree"
            case b"10":
                type = "blob"
            case b"12":
                type = "blob"
            case b"16":
                type = "commit"
            case _:
                raise Exception(f"Weird tree leaf mode {item.mode}")

        if not (recursive and type == "tree"):
            print(
                f"{'0' * (6 - len(item.mode)) + item.mode.decode('ascii')} {type} {item.sha}\t{os.path.join(prefix, item.path)}"
            )
        else:
            ls_tree(repo, item.sha, recursive, os.path.join(prefix, item.path))

