from repository import GitRepository , repo_file ,repo_dir, repo_find
from storage import object_find,object_write
from objects import GitTag
import os
from typing import Optional, Dict, Any

def ref_resolve(repo: GitRepository, ref: str) -> Optional[str]:
    """Resolve a reference to its SHA hash.

    Args:
        repo: The Git repository instance.
        ref: The reference name (e.g., 'HEAD', 'refs/heads/master').

    Returns:
        The SHA hash string if the reference is found, None otherwise.
    """
    path = repo_file(repo, ref)
    
    if not os.path.isfile(path):
        return None
    
    with open(path,'r') as fp:
        data = fp.read()[:-1] # drop \n
        
    if data.startswith("ref: "):
        return ref_resolve(repo , data[5:])
    else:
        return data
    
        
def ref_list(repo: GitRepository, current_path: Optional[str] = None) -> Dict[str, Any]:
    """List all references in the repository.

    Args:
        repo: The Git repository instance.
        current_path: The path to start listing from (defaults to 'refs').

    Returns:
        A nested dictionary of references.
    """
    if not current_path :
        current_path = repo_dir(repo, "refs")
        
    references  = dict()
    
    for entry_name  in sorted(os.listdir(current_path)):
        
        entry_path = os.path.join(current_path , entry_name )
        
        if os.path.isdir(entry_path):
            references [entry_name] = ref_list(repo,entry_path)
        else :
            references [entry_name] = ref_resolve(repo,entry_path)
            
    return references 


def show_ref(repo: GitRepository, refs: Dict[str, Any], include_hash: bool = True, current_prefix: str = "") -> None:
    """Display references in a formatted way.

    Args:
        repo: The Git repository instance.
        refs: The dictionary of references.
        include_hash: Whether to include SHA hashes in output.
        current_prefix: The current prefix for nested references.
    """
    # add "/" if we are not at the rool level
    if current_prefix : 
        current_prefix = current_prefix + "/"
        
    for ref_name, ref_value in refs.items():
        # this is a file (final ref -> sha string)
        if isinstance(ref_value , str) :
            if include_hash:
                print(f"{ref_value} {current_prefix}{ref_name}")
            else :
                print(f"{current_prefix}{ref_name}")
                
        else :  # this is directory (nested ref)
            show_ref(
                repo,
                ref_value,
                include_hash=include_hash,
                current_prefix=f"{current_prefix}{ref_name}"
            )
            


def tag_create(repo: GitRepository, tag_name: str, target_ref: str = "HEAD", create_annotated_tag: bool = False, message: bytes = b"A tag generated by gitsh") -> None:
    """Create a new tag in the repository.

    Args:
        repo: The Git repository instance.
        tag_name: The name of the tag.
        target_ref: The reference to tag (default 'HEAD').
        create_annotated_tag: Whether to create an annotated tag.
        message: The tag message for annotated tags.
    """
    # find the gitobject from reference
    target_sha =object_find(repo,target_ref)
    
    if create_annotated_tag : 
        # create tag object
        tag = GitTag()
        
        tag.kvlm = dict()
        
        tag.kvlm[b"object"] =target_sha.encode()
        tag.kvlm[b"type"] = b'commit'
        tag.kvlm[b"tag"] = tag_name.encode()
        
        # add tagger details 
        name = repo.config.get("user", "name")
        email = repo.config.get("user", "email")
        tagger =f"{name} <{email}>".encode() if name and email else b'gitsh <gitsh@example.com>'
        tag.kvlm[b'tagger'] =  tagger
        
        # add message
        tag.kvlm[None] =message
        # write the tag object to git database
        tag_object_sha  =object_write(tag,repo)
        
        
        # create reference pointing to the tag object
        ref_create(repo, "tags/" + tag_name , tag_object_sha )
        
    else: 
        # lightweight tag 
        ref_create(repo , "tags/"+tag_name , target_sha)
        
        
def ref_create(repo: GitRepository, ref_name: str, sha_value: str) -> None:
    """Create a new reference.

    Args:
        repo: The Git repository instance.
        ref_name: The name of the reference.
        sha_value: The SHA hash to point to.
    """
    with open(repo_file(repo , "refs/" +ref_name) , "w") as ref_file:
        ref_file.write(sha_value + "\n")
    
repo = repo_find()
tag_create(repo,"v1.0.0")