import Commit
import Utils 
import Repository 
class GitTag(Commit.GitCommit):
    fmt = b"tag"

def tag_create(repo , tag_name , target_ref="HEAD" , create_annotated_tag= False,message =b"A tag generated by gitsh"):
    # find the gitobject from reference
    target_sha =Utils.object_find(repo,target_ref)
    
    if create_annotated_tag : 
        # create tag object
        tag = GitTag()
        
        tag.kvlm = dict()
        
        tag.kvlm[b"object"] =target_sha.encode()
        tag.kvlm[b"type"] = b'commit'
        tag.kvlm[b"tag"] = tag_name.encode()
        
        # add tagger details 
        name = repo.config.get("user", "name")
        email = repo.config.get("user", "email")
        tagger =f"{name} <{email}>".encode() if name and email else b'gitsh <gitsh@example.com>'
        tag.kvlm[b'tagger'] =  tagger
        
        # add message
        tag.kvlm[None] =message
        # write the tag object to git database
        tag_object_sha  =Utils.object_write(tag,repo)
        
        
        # create reference pointing to the tag object
        ref_create(repo, "tag/" + tag_name , tag_object_sha )
        
    else: 
        # lightweight tag 
        ref_create(repo , "tag/"+tag_name , target_sha)
        
        
def ref_create(repo , ref_name , sha_value):
    with open(Repository.repo_file(repo , "refs/" +ref_name) , "w") as ref_file:
        ref_file.write(sha_value + "\n")
    
    
repo = Repository.repo_find(".", required=True)
tag_create(
    repo,
    "v2.0.0",
    "HEAD",
    True
)